'use client';

import './globals.css'
import type { Metadata } from 'next'
import Navbar from './components/Navbar'
import { SessionProvider } from 'next-auth/react'

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <SessionProvider>
      <Navbar />
      <body>{children}</body>
      </SessionProvider>
    </html>
  )
}
